import comp from './comp.png' 
import logo from './logo.png'
import bg from './noise-texture.png'
import insta from './instagram.png'
import whatsapp from './whats-app.png'
import linkedIn from './Linked-in.png'
import profile_icon from './profile_icon.png'
import github from './github.png'

import header from './header.png'
import Hackathon from './isometric-design-business-people-meeting.png'
import comingsoon from './modern-coming-soon-poster-with-stay-tuned-message.png'
import Coding from './pair-programming-concept-illustration.png'
import competitions from './competitions.jpeg'
import community from './community.png'
import workshop from './workshop.png'
import mentoring from './mentoring.png'
import braces from './braces.png'

import ankana from './team/Ankana_Roy.jpg'
import anushka from './team/Anushka_Roy.jpg'
import chanakya from './team/Chanakya_Kasa.jpg'
import deekshitha from './team/Deekshitha_R.jpg'
import deepthi from './team/Deepthi_P.jpg'
import gauri from './team/Gauri_Sahni.jpg'
import harshita from './team/Harshita_Harihar.jpg'
import kashyap from './team/B_Sai_Kashyap.jpg'
import lohith from './team/Lohith.jpg'
import mahalakshmi from './team/Mahalakshmi.jpg'
import mohit from './team/Mohit_Kumar.jpg'
import pritam from './team/Pritam_Dhar.jpg'
import rachan from './team/RachanMurthy.jpeg'
import rahul from './team/Rahul_Raj.jpeg'
import rakshitha from './team/Rakshitha_S.jpeg'
import satwik from './team/SATWIK _M_BADIGER.jpg'
import satyam from './team/Satyam_Gupta.png'
import sharlet from './team/Sharlet_Alex.jpg'
import tarun from './team/Tarun.png'
import monish from './team/Sp_Monish.jpeg'
import anjum from './team/T_S_ANJUM_KAUSAR.jpeg'
import umaiza from './team/Umaiza_Fathima.jpeg'
import vivith from './team/Vivith_Rajiv_Kanchi.jpg'
import venkateshwara from './team/Venkateshwara_Reddy.jpg'
import yash from './team/Yash_Agarwal.jpg'


export default { profile_icon,comp, logo, bg, insta, whatsapp, linkedIn, github, header, Hackathon, comingsoon, Coding, competitions, community, workshop, mentoring, braces, ankana, anushka, chanakya, deekshitha, deepthi, gauri, harshita,kashyap , lohith, mahalakshmi, mohit, pritam, rachan, rahul, rakshitha, satwik, satyam, sharlet, tarun, monish, anjum, umaiza,vivith , venkateshwara, yash }
